### ISSUE TITLE
Support different interface names on all interfaces

### ISSUE THREAD

**Issue by dougszumski** [stackhpc/kayobe-original#115]
# Overview

On multi node deployments interfaces may have different names. For example, the ```api_interface``` may be called ```breno1``` on one host, and ```eno1``` on another. Support has been added for this in this [PR](https://github.com/stackhpc/kayobe/pull/114), however other interfaces are assumed to be in-variate across hosts.

# Enhancement

Support all interfaces and write the variables to an inventory/host_vars/<host> file. Hard code the interface variable names rather than adding them to the pass through vars list.

**Comment by markgoddard** [comment]
Moved to storyboard: https://storyboard.openstack.org/#!/story/2001658
