### ISSUE TITLE
Apply upper-constraints when installing OpenStack python packages

### ISSUE THREAD

**Issue by markgoddard** [stackhpc/kayobe-original#128]
# Overview

When installing OpenStack python packages it is recommended to use an upper constraints file to place an upper limit on dependent package versions. In particular this applies to kolla and kolla-ansible.

See https://github.com/openstack/bifrost/blob/0809195f01736f5729f8b991e1e2330d0de81a09/playbooks/roles/bifrost-ironic-install/tasks/install.yml#L54 for an example of how this is done in bifrost.

**Comment by dougszumski** [comment]
See #129

**Comment by dougszumski** [comment]
This should be fixed now.
