### ISSUE TITLE
Network not found: no network with matching name 'management'

### ISSUE THREAD

**Issue by xiaoruiguo** [stackhpc/kayobe-original#149]
TASK [stackhpc.libvirt-vm : Ensure the VM is running and started at boot] *************************************************************************************************
fatal: [control]: FAILED! => {"changed": false, "failed": true, "msg": "Network not found: no network with matching name 'management'"}

I config references http://kayobe.readthedocs.io/en/latest/configuration/network.html.

run: kayobe seed vm provision

**Comment by ktibi** [comment]
Hi @xiaoruiguo 

can you open a  bug in storyboard ? https://storyboard.openstack.org/#!/project/928

And don't forget to paste your configuration (kayobe-config)

You can go too on #openstack-kayobe on IRC for support and help.

Thx ;)

**Comment by markgoddard** [comment]
Please open a bug in storyboard, or reply here, or get in touch on IRC.
