### ISSUE TITLE
Enable deployment of Nova Compute hosts to provide virtual machines

### ISSUE THREAD

**Issue by darrylweaver** [stackhpc/kayobe-original#47]
Allow deployment of a Nova Compute node to act as a virtual machine host to allow deployment of standard virtual machines in the same region (and connected to the same network) as ironic bare metal hosts.

**Comment by markgoddard** [comment]
Work in progress here: https://github.com/markgoddard/kayobe/tree/add-compute-group, being tested and honed by @ktibi.

**Comment by ktibi** [comment]
Kolla-ansible have Fix for qemu and centos
https://review.openstack.org/#/c/506529/8/ansible/roles/nova/templates/qemu.conf.j2

**Comment by ktibi** [comment]
@markgoddard we can close this issue, after many deploys, everything is working.

**Comment by markgoddard** [comment]
We haven't tested mixed virt and bare metal, which was the original request, but let's close this and open tickets for any other issues encountered when that is tested.
