### ISSUE TITLE
Support extension points for custom behaviour

### ISSUE THREAD

**Issue by markgoddard** [stackhpc/kayobe-original#52]
## Overview
Kayobe should provide extension mechanisms that allow an operator to apply arbitrary configuration to their cloud, without requiring explicit support in kayobe.

## User Stories
1. As a cloud admin, I want to provide extension points as custom ansible playbooks and roles along with my configuration.
2. As a cloud admin, I want to run specific extensions on demand, by playbook name.
3. As a cloud admin, I want to use hooks that run extensions at specific points in the existing deployment flow.
4. As a cloud admin, I want to add custom kayobe commands to perform custom tasks using extensions.

### User Story 1
Provide a well-known location within `kayobe-config` (or other?) for playbooks and roles:

    ${KAYOBE_CONFIG_PATH}/ansible/*.yml
    ${KAYOBE_CONFIG_PATH}/ansible/roles/

Provide a mechanism to ensure that playbooks on this path can use kayobe's playbook group variables. Ensure

### User Story 2
Provide a kayobe command to run extensions by playbook name.

### User Story 3
Define a set of hook points (pre-overcloud host configure, post-overcloud service deploy, etc.). Provide a well-known location within `kayobe-config` (or other?) for hooks:

    ${KAYOBE_CONFIG_PATH}/hooks/*.yml

### User story 4
Define the supported API of the kayobe python module. Allow extension through Cliff commands as python entry points under `kayobe.cli`.

**Comment by dougszumski** [comment]
Looks good to me. As discussed, some things that could make use of this:

- Configuring roles, and users for monitoring services
- Deploying os-capacity
- Deploying monitoring framework until it's integrated into kolla/kayobe

**Comment by markgoddard** [comment]
Migrated to storyboard: https://storyboard.openstack.org/#!/story/2001663
