### ISSUE TITLE
Enable Kayobe to deploy keystone policy.json file

### ISSUE THREAD

**Issue by darrylweaver** [stackhpc/kayobe-original#60]
We would like to be able to deploy a custom keystone policy.json file.
This is supported in kolla, but needs to be enabled in Kayobe.

**Comment by markgoddard** [comment]
This should be supported in kayobe already.

* Add `policy.json` to `kayobe-config/etc/kayobe/kolla/config/keystone/`
* `kayobe overcloud service reconfigure -kt keystone`

I have some documentation on this in progress.
